#GENERAL
spring:
  datasource:
    url: jdbc:postgresql://devdb:5434/gtsaude
    username: gtsaude-${spring.application.name}
    password: gtsaude
    hikari:
      maximum-pool-size: 3

#OAUTH2
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      access-token-uri: http://gtsaude.sbox.me/usuario/oauth/token
      user-authorization-uri: http://gtsaude.sbox.me/usuario/oauth/authorize
    resource:
      user-info-uri: http://gtsaude.sbox.me/usuario/api/principal
