#GENERAL
spring:
  datasource:
    url: jdbc:postgresql://devdb:5434/vigentee

#OAUTH2
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      access-token-uri: http://vigentee.sbox.me/usuario/oauth/token
      user-authorization-uri: http://vigentee.sbox.me/usuario/oauth/authorize
    resource:
      user-info-uri: http://vigentee.sbox.me/usuario/api/principal
