#GENERAL
spring:
  datasource:
    url: jdbc:postgresql://devdb:5434/vigiepi

#OAUTH2
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      access-token-uri: http://vigiepi.sbox.me/usuario/oauth/token
      user-authorization-uri: http://vigiepi.sbox.me/usuario/oauth/authorize
    resource:
      user-info-uri: http://vigiepi.sbox.me/usuario/api/principal

#URL
url.context: http://vigiepi.sbox.me