spring:
#DATA SOURCE
  datasource:
    url: jdbc:postgresql://<DOCKER_IP>:5432/gtsaude
    username: gtsaude
    password: gtsaude
#JPA
  jpa:
    hibernate:
      ddl-auto: validate
#MAIL
  mail:
    host: info-projetos.pti.org.br
    port: 587
    username: vigentee@pcr-ccz.pti.net.br
    password: N86259qMPC94B8F
    from: rede-vigentee@<DOMINIO>
    properties:
      mail.smtp.starttls.enable: false
      mail.properties.mail.smtp.starttls.required: false
      mail.properties.mail.smtp.ssl.enable: false
      mail.properties.mail.smtps.debug: true
      mail.properties.mail.smtp.debug: true
      mail.properties.mail.debug: true
#OAUTH2
security:
  oauth2:
    sso:
      loginPath: /autenticacao
    client:
      client-id: ${spring.application.name}
      client-secret:
      client-authentication-scheme: form
      access-token-uri: http://<DOCKER_IP>:8080/usuario/oauth/token
      user-authorization-uri: http://<DOMINIO>/usuario/oauth/authorize
    resource:
      id: ${spring.application.name}
      service-id: ${spring.application.name}-resource
      user-info-uri: http://<DOCKER_IP>:8080/usuario/api/principal
      prefer-token-info: false
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAihRoCostoZBy0pZhlHfalgaspU7RWpthsA4nFdixmEbJlJBVwwU8Eo29Gm2+EP9MVNDbPI43aDLcWoEjIhyfd7Oejtvz8H/30nVigdrL1UnMOloqEWKvg1rYhYcsayWoL6kZJrPuEeoagByG9W0lNtSWExgrSksgkwexUOG69wYKtCrIuwgtiJAEbNhXCEZOiR8zBI2Jm5JcWmnN5oVjOA6j4279fkIvil24ITbPqM4Jff9iehgRoR3NAnXJPcKpiiQ83LdnGFQqdmxFcXSf3DCy498PV2Jsog1KsEaKL+FWQiAN5QNKOvFiFQkxEfOvykW5IyQbA5kURVOV01h2vQIDAQAB
          -----END PUBLIC KEY-----
#URL
url.context: http://<DOMINIO>
