#DATA SOURCE 
spring:
  jpa:
    properties:
      hibernate:
        dialect: br.com.gtsaude.common.infrastructure.hibernate.dialect.PostgisDialect
  hikari:
    maximum-pool-size: 3

#WEB CONTAINER
server:
  port: 8084